# Generated by Django 4.0.5 on 2022-06-23 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200, verbose_name='nome da receita')),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField(verbose_name='tempo de preparo')),
                ('rendimento', models.CharField(max_length=50)),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('publicada', models.BooleanField(default=False)),
                ('foto_receita', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('categoria', models.ManyToManyField(default='Sem categoria', related_name='receitas', to='receitas.categoria')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
        ),
    ]
