# Generated by Django 4.0.5 on 2022-06-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receitas', '0002_receita_pessoa_receita_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='data_receita',
            new_name='data_publicacao',
        ),
        migrations.AddField(
            model_name='receita',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=200, verbose_name='nome da receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='pessoas.pessoa', verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='tempo de preparo'),
        ),
    ]
