# Generated by Django 4.0.5 on 2022-06-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_rename_data_receita_receita_data_publicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.ManyToManyField(default='Sem categoria', related_name='receitas', to='receitas.categoria'),
        ),
    ]
